#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &

export HTTP_CLIENT="wget --no-check-certificate -O"
export PORT=$OPENSHIFT_INTERNAL_PORT
export HOST=$OPENSHIFT_INTERNAL_IP
export HOME=$OPENSHIFT_DATA_DIR
export DB_NAME=learnsmthng_production
export DB_HOST=$OPENSHIFT_POSTGRESQL_DB_HOST
export DB_PORT=$OPENSHIFT_POSTGRESQL_DB_PORT
export DB_PASSWORD=$OPENSHIFT_POSTGRESQL_DB_PASSWORD
export DB_USERNAME=$OPENSHIFT_POSTGRESQL_DB_USERNAME
export LEIN_JVM_OPTS=-Duser.home=$HOME

cd $OPENSHIFT_REPO_DIR

$OPENSHIFT_REPO_DIR/bin/lein migrate >${OPENSHIFT_DIY_LOG_DIR}/lein.log 2>&1
$OPENSHIFT_REPO_DIR/bin/lein trampoline run >${OPENSHIFT_DIY_LOG_DIR}/lein.log 2>&1 &
disown
